Components/NavbarMenuViewComponent.cs
using Flexify.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Flexify.Components
{
    public class NavbarMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var links = new List<NavLinkModel>
            {
                new NavLinkModel { Url = "/App", Name="Home", Controller="App"},
                new NavLinkModel { Url = "/App/Appearance", Name="Appearance",Controller="App"},
                new NavLinkModel { Url = "/App/Post", Name="Post", Controller = "App"},
                new NavLinkModel { Url = "/App/Account", Name="Settings",Controller="App"},
                new NavLinkModel { Url = "/auth/logout", Name="Logout", Controller = "Auth"},
            };
            return View(links);
        }
    }
}

Views/App/Account.cshtml
@model UserModel;

@{
    ViewData["Title"] = "Account";
}
<div class="p-10">
    @await Component.InvokeAsync("NavbarMenu")
    <main class="w-full mt-10 mx-auto max-w-4xl">
      <div class="">
        <h1 class="text-lg font-semibold">Profile</h1>
            @if (TempData["Success"] != null)
            { <div class="text-center text-green-500 mb-3">
                    @TempData["Success"]
                </div>
            }
            @if (TempData["Error"] != null)
            {
                <div class="text-center text-red-500 mb-3">
                    @TempData["Error"]
                </div>
            }
        <form asp-action="Account" method="post" class="border border-gray-200 p-5 bg-white rounded-md">
          <div class="flex gap-4 items-center">
            <div
              class="shrink-0 bg-gray-700 w-24 h-24 rounded-full flex items-center justify-center text-white"
            >
              @Model?.FirstName?[0]
            </div>
            <div class="w-full flex flex-col gap-4">
              <div
                class="font-medium border border-gray-300 px-3 p-4 rounded-md w-full text-center"
              >
                Add a picture
              </div>
              <div
                class="bg-gray-700 text-white border border-gray-300 px-3 p-4 rounded-md w-full text-center"
              >
                Remove picture
              </div>
            </div>
          </div>

          <div class="flex flex-col gap-3 mt-5">
            <div class="grid grid-cols-2 gap-3">
              <div class="bg-gray-200 p-2 rounded-md flex flex-col items-start">
                <label class="text-xs">First Name</label>
                <input asp-for="FirstName"
                  type="text"
                  class="bg-transparent text-sm w-full"
                  value="@Model.FirstName"
                />
              </div>
              <div class="bg-gray-200 p-2 rounded-md flex flex-col items-start">
                <label class="text-xs">Last Name</label>
                <input asp-for="LastName"
                  type="text"
                  class="bg-transparent text-sm w-full"
                                   value="@Model.LastName" />
              </div>
            </div>
            <div class="bg-gray-200 p-2 rounded-md flex flex-col items-start">
              <label class="text-xs">Username</label>
              <input asp-for="Username"
                type="text"
                class="bg-transparent text-sm w-full"
                value="@Model.Username"
              />
            </div>
            <div class="bg-gray-200 p-2 rounded-md flex flex-col items-start">
              <label class="text-xs">Email</label>
              <input asp-for="Email"
                type="text"
                class="bg-transparent text-sm w-full"
                value="@Model.Email"
              />
            </div>
                    <div class="">
                        <span class="text-blue-500 text-sm">Enter password to save changes</span>
                    </div>
            <div class="bg-gray-200 p-2 rounded-md flex flex-col items-start">
              <label class="text-xs">Enter Password</label>
              <input asp-for="Password"
                type="password"
                class="bg-transparent text-sm w-full outline-none"
                value=""
                placeholder=""
              />
                        <span asp-validation-for="Password"  class="text-red-600 absolute text-danger top-[-22px]"></span>
            </div>
            
            <div class="flex justify-end">
              <button class="bg-blue-500 text-white px-3 p-2 rounded-md">
                Save Changes
              </button>
            </div>
          </div>
        </form>
            <div class="flex justify-end flex-col gap-3 mt-5">
                <form asp-action="DeleteAccount" method="post">
                    <button type="submit" class="bg-red-500 text-white px-3 p-2 rounded-md">Delete Account</button>
                </form>
            
            </div>
      </div>
       
    </main>
</div>

Views/App/Index.cshtml
@model UserModel
@{
    ViewData["Title"] = "Dashboard";
}

<div class="text-center p-10">
    @await Component.InvokeAsync("NavbarMenu")

    <div class="max-w-4xl gap-10 mx-auto flex flex-col justify-center mt-10">
        <div class="bg-white shadow-sm w-full border p-5 flex flex-col gap-3 items-center bg-white rounded-lg">
            <h1 class="font-medium">Lifetime Analytics</h1>
            <ul class="flex items-center gap-4">
                <li class="flex items-center gap-1 text-sm">
                    <div class="h-2 w-2 bg-green-500 rounded-full text-green-500"></div>
                    <span>Views: 21 </span>
                </li>
                 <li class="flex items-center gap-1 text-sm">
                    <div class="h-2 w-2 bg-orange-500 rounded-full text-green-500"></div>
                    <span>Clicks: 104 </span>
                </li>
                <li class="flex items-center gap-1 text-sm">
                    <div class="h-2 w-2 bg-blue-500 rounded-full text-green-500"></div>
                    <span>Links: 5</span>
                </li>
            </ul>
        </div>
        <section class="w-full flex flex-col gap-4 items-start self-start ">
            <h1 class="font-medium">Top Performing Links</h1>
            <div class="bg-white rounded-md p-5 border flex flex-col gap-4 w-full">
                <div class="flex justify-between text-sm text-slate-600">
                    <label></label>
                    <span>Clicks</span>
                </div>
                <div class="justify-between flex items-center text-sm">
                    <label>About Page</label>
                    <span>500</span>
                </div>
                <div class="justify-between flex items-center text-sm">
                    <label>Contact</label>
                    <span>235</span>
                </div>
                <div class="justify-between flex items-center text-sm">
                    <label>My Games</label>
                    <span>340</span>
                </div>
                <div class="justify-between flex items-center text-sm">
                    <label>Tiktok Shop</label>
                    <span>500</span>
                </div>
                <div class="justify-between flex items-center text-sm">
                    <label>Shopee Shop</label>
                    <span>500</span>
                </div>
            </div>
        </section>
    </div>
</div>

Views/App/Post.cshtml
@model UserModel;
@{
    ViewData["Title"] = "Post";
}

<div class="p-10 bg-slate-100">
    @await Component.InvokeAsync("NavbarMenu")
</div>